PySchool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import accounts
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('core/', include('core.urls')),
    path('settings/', include('settings.urls')),
    path('tinymce', include('tinymce.urls')),
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('accounts/profile/', accounts.views.profile, name='profile'),
    path('accounts/profile/update', accounts.views.profile_update, name='profile_update'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from .views import CreateCheckoutSessionView

urlpatterns = [
    path('courses', views.courses, name='courses'),
    path('payment-successful', views.payment_successful, name='payment-successful'),
    path('read-cat/<int:id>', views.read_cat, name='read-cat'),
    path('favorite/<slug:slug>', views.favorite, name='favorite'),
    path('search', views.search, name='search'),
    path('subscription', views.subscription, name='subscription'),
    path('confirm-subscription/<int:id>/', views.confirm_subscription, name="confirm-subscription"),
    path('subscription-complete/', views.subscription_complete, name="subscription-complete"),
    path('404', views.page_not_found, name='404'),
    path('course/filter-data', views.filter_data, name="filter-data"),
    path('course/<slug:slug>', views.course_details, name='course_details'),
    path('checkout/<slug:slug>', views.checkout, name='checkout'),
    path('paypal-checkout/<slug:slug>', views.paypal_checkout, name='paypal-checkout'),
    path('my-courses', views.my_courses, name='my-courses'),
    path('my-reviews', views.my_reviews, name='my-reviews'),
    path('complete/', views.payment_complete, name="complete"),
    path('course/course-take/<slug:slug>', views.course_take, name='course-take'),
    path('review/<slug:slug>', views.review, name='review'),
    path('submit-review/<slug:slug>/', views.submit_review, name='submit-review'),

    path('stripe-page/<slug:slug>', views.stripe_page, name='stripe-page'),
    path('create-checkout-session/<slug:slug>', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('stripe-payment-success', views.stripe_payment_success, name='stripe-payment-success'),

    path('stripe-success/<slug:slug>', views.stripe_success, name='stripe-success'),
    path('stripe-payment-cancelled', views.stripe_payment_cancelled, name='stripe-payment-cancelled'),
    path('webhook/stripe', views.my_webhook_view, name='webhook-stripe'),
]

core/models.py
from django.db import models
from django.db.models import Avg, Count
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth import get_user_model
from tinymce import models as tinymce_models
User = get_user_model()


# this function validates image dimensions
def validate_image(image):
    max_height = 1920
    max_width = 1080
    height = image.file.height
    width = image.file.width
    if width > max_width or height > max_height:
        raise ValidationError("Height or Width is larger than what is allowed")


class Category(models.Model):
    icon = models.CharField(max_length=200, null=True, blank=True, help_text='example: fa-brands fa-angular')
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

    def get_all_categories(self):
        return Category.objects.all().order_by('-id')


class Author(models.Model):
    author_profile = models.ImageField(upload_to='media/authors')
    name = models.ForeignKey(User, models.CASCADE, null=True)
    about_author = models.TextField()
    facebook_link = models.URLField(max_length=1023, null=True)
    x_link = models.URLField(max_length=1023, null=True)
    instagram_link = models.URLField(max_length=1023, null=True)
    youtube_link = models.URLField(max_length=1023, null=True)

    def __str__(self):
        return str(self.name)


class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Course(models.Model):
    STATUS = (
        ('PUBLISHED', 'NORMAL'),
        ('DRAFT', 'DRAFT'),
        ('LATEST', 'lATEST'),
        ('FEATURED', 'FEATURED'),
        ('POPULAR', 'POPULAR'),
    )
    CERTIFICATES = (
        ('Yes', 'Yes'),
        ('No', 'No'),
    )
    FEATURED_AS = (
        ('0', 'NORMAL'),
        ('3', 'NEW'),
        ('2', 'HOT'),
        ('1', 'BESTSELLER')
    )
    title = models.CharField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    description = tinymce_models.HTMLField()
    featured_image = models.ImageField(upload_to='media/featured_image', null=True, help_text='Recommended Dimensions: 1000 x 600')
    featured_video = models.CharField(max_length=300, null=True, help_text='eg: https://www.youtube.com/watch?v=6stlCkUDG_s&list=PL4Gr5tOAPttLOY9IrWVjJlv4CtkYI5cI_')
    price = models.FloatField(max_length=6, default=0)
    discount = models.IntegerField(null=True, default=0, blank=0, help_text='discount is %, put 0 if it has no discount')
    discounted_until = models.DateTimeField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    level = models.ForeignKey(Level, on_delete=models.CASCADE, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    certificate = models.CharField(choices=CERTIFICATES, max_length=100, null=True)
    slug = models.SlugField(default='', max_length=400, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=100, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    featured_as = models.CharField(choices=FEATURED_AS, max_length=100, null=True)

    def __str__(self):
        return self.title

    # calculating average review
    def average_review(self):
        reviews = Review.objects.filter(course=self).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg=float(reviews['average'])
        return avg

    def count_review(self):
        reviews = Review.objects.filter(course=self).aggregate(count=Count('course_id'))
        cnt = 0
        if reviews['count'] is not None:
            cnt = int(reviews['count'])
        return cnt

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("course_details", kwargs={'slug': self.slug})

    def get_checkout_url(self):
        from django.urls import reverse
        return reverse("checkout", kwargs={'slug': self.slug})

    def get_paypal_checkout_url(self):
        from django.urls import reverse
        return reverse("paypal-checkout", kwargs={'slug': self.slug})

    def get_stripe_checkout_url(self):
        from django.urls import reverse
        return reverse("stripe-page", kwargs={'slug': self.slug})

    def get_stripe_success_url(self):
        from django.urls import reverse
        return reverse("stripe-success", kwargs={'slug': self.slug})

    def get_watch_url(self):
        from django.urls import reverse
        return reverse("course-take", kwargs={'slug': self.slug})

    def get_review_url(self):
        from django.urls import reverse
        return reverse("review", kwargs={'slug': self.slug})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, Course)


class WhatToLearn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Requirement(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Section(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " - " + self.course.title


class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to='media/video_thumbnail', null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    youtube_video_id = models.CharField(max_length=100, null=True, blank=True, help_text='Eg: 9iKZ_uojvxw')
    time_duration = models.FloatField(null=True, default=0)
    preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    has_completed = models.BooleanField(default=False)
    progress = models.IntegerField(default=0)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title


# class Payment(models.Model):
#     order_id = models.CharField(max_length=100, null=True, blank=True)
#     payment_id = models.CharField(max_length=100, null=True, blank=True)
#     user_course = models.ForeignKey(UserCourse, on_delete=models.CASCADE, null=True)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#     date = models.DateTimeField(auto_now_add=True)
#     status = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.user.first_name + " - " + self.course.title


class Subscription(models.Model):
    VALIDITY = (
        ('Monthly', 'Monthly'),
        ('Yearly', 'Yearly'),
        ('Lifetime', 'Lifetime')
    )
    plan = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=5, null=True, blank=True, decimal_places=2)
    popular = models.BooleanField(default=False)
    validity = models.CharField(choices=VALIDITY, max_length=100, null=True)

    def get_subscription_url(self):
        from django.urls import reverse
        return reverse("confirm-subscription", kwargs={'id': self.id})

    def __str__(self):
        return self.plan


class Features(models.Model):
    package = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    feature = models.CharField(max_length=500)

    class Meta:
        verbose_name_plural = "Features"

    def __str__(self):
        return self.package.plan


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    subscription = models.ForeignKey(Subscription, max_length=200, null=True, blank=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subscription.plan


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review_id = models.AutoField(primary_key=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    comment = tinymce_models.HTMLField(max_length=500, null=True)
    rating = models.IntegerField(default=0, null=True)
    rating_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title

templates/core/course-take.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Lesson - Online Courses & Education Bootstrap5 Template</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png">

<!-- CSS
	============================================ -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/sal.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/feather.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/euclid-circulara.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/magnify.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/odometer.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/animation.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/magnigy-popup.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plyr.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body class="rbt-header-sticky">

    <div class="rbt-lesson-area bg-color-white">
        <div class="rbt-lesson-content-wrapper">
            <div class="rbt-lesson-leftsidebar">
                <div class="rbt-course-feature-inner rbt-search-activation">
                    <div class="section-title">
                        <h4 class="rbt-title-style-3">Course Content</h4>
                    </div>
                    <hr class="mt--10">
                    <div class="rbt-accordion-style rbt-accordion-02 for-right-content accordion">
                        <div class="accordion" id="accordionExampleb2">
                            {% for section in course.section_set.all%}
                            <div class="accordion-item card">
                                <h2 class="accordion-header card-header" id="headingTwo1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" aria-expanded="true" data-bs-target="#id{{section.id}}" aria-controls="collapseTwo1">
                                        {{ section.name }} <span class="rbt-badge-5 ml--10">1/2</span>
                                    </button>
                                </h2>
                                {% for video in section.video_set.all %}
                                <div id="id{{video.section.id}}" class="accordion-collapse collapse show" aria-labelledby="headingTwo1">
                                    <div class="accordion-body card-body">
                                        <ul class="rbt-course-main-content liststyle">
                                            <li>
                                                {% if check_enroll is not None %}
                                                <a href="?lecture={{video.id}}">
                                                    <div class="course-content-left">
                                                        <i class="feather-play-circle"></i> <span class="text">{{video.title}}</span>
                                                    </div>
                                                    <div class="course-content-right">
                                                        <span class="min-lable">{{video.time_duration}} min</span>
                                                    </div>
                                                </a>
                                                {% else %}
                                                    {% if video.preview == True %}
                                                    <a href="?lecture={{video.id}}">
                                                        <div class="course-content-left">
                                                            <i class="feather-play-circle"></i> <span class="text">{{video.title}}</span>
                                                        </div>
                                                        <div class="course-content-right">
                                                            <span class="rbt-badge variation-03 bg-primary-opacity"><i class="feather-eye"></i> Preview</span>
                                                            <span class="min-lable">{{video.time_duration}} min</span>
                                                        </div>
                                                    </a>
                                                    {% else %}
                                                    <a href="#" aria-disabled="true">
                                                        <div class="course-content-left">
                                                            <i class="feather-play-circle"></i> <span class="text" data-toggle="tooltip" title="Enroll to this Course First">{{video.title}}</span>
                                                        </div>
                                                        <div class="course-content-right">
                                                            <span class="min-lable">{{video.time_duration}} min</span>
                                                        </div>
                                                    </a>
                                                    {% endif%}
                                                {% endif %}
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="rbt-lesson-rightsidebar overflow-hidden lesson-video">
                <div class="lesson-top-bar">
                    <div class="lesson-top-left">
                        <div class="rbt-lesson-toggle">
                            <button class="lesson-toggle-active btn-round-white-opacity" title="Toggle Sidebar"><i class="feather-arrow-left"></i></button>
                        </div>
                        {% if video.id %}
                        <h5>{{ video.section.name}} >>> {{video.title}}</h5>
                        {% else %}
                        <h5>{{course.title}}</h5>
                        {% endif %}
                    </div>
                    <div class="lesson-top-right">
                        <div class="rbt-btn-close">
                            <a href="{{course.get_absolute_url}}" title="Go Back to Course Details" class="rbt-round-btn"><i class="feather-x"></i></a>
                        </div>
                    </div>
                </div>
                <div class="inner">
                    {% if video.id %}
                    <div class="plyr__video-embed rbtplayer">
                        <iframe src="https://www.youtube.com/embed/{{video.video_url}}" allowfullscreen allow="autoplay"></iframe>
                    </div>
                    {% else %}
                    <div class="plyr__video-embed rbtplayer">
                        <iframe src="https://www.youtube.com/embed/{{course.featured_video}}" allowfullscreen allow="autoplay"></iframe>
                    </div>
                    {% endif %}
                    <div class="content">
                        <div class="section-title">
                            {% if check_review is None %}
                            <div class="bg-color-extra2 ptb--15 overflow-hidden">
                                <div class="rbt-button-group">

                                    <a class="rbt-btn icon-hover btn-md" href="{% url 'review' course.slug%}">
                                        <span class="btn-text">Rate this Course</span>
                                        <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                    </a>
                                </div>
                            </div>
                            {% else %}

                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="rbt-progress-parent">
        <svg class="rbt-back-circle svg-inner" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
        </svg>
    </div>
<!-- JS
============================================ -->
<!-- Modernizer JS -->
<script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
<!-- jQuery JS -->
<script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
<!-- sal.js' %} -->
<script src="{% static 'assets/js/vendor/sal.js' %}"></script>
<script src="{% static 'assets/js/vendor/swiper.js' %}"></script>
<script src="{% static 'assets/js/vendor/magnify.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-appear.js' %}"></script>
<script src="{% static 'assets/js/vendor/odometer.js' %}"></script>
<script src="{% static 'assets/js/vendor/backtotop.js' %}"></script>
<script src="{% static 'assets/js/vendor/isotop.js' %}"></script>
<script src="{% static 'assets/js/vendor/imageloaded.js' %}"></script>

<script src="{% static 'assets/js/vendor/wow.js' %}"></script>
<script src="{% static 'assets/js/vendor/waypoint.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/easypie.js' %}"></script>
<script src="{% static 'assets/js/vendor/text-type.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-one-page-nav.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-ui.js' %}"></script>
<script src="{% static 'assets/js/vendor/magnify-popup.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/paralax-scroll.js' %}"></script>
<script src="{% static 'assets/js/vendor/paralax.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/countdown.js' %}"></script>
<script src="{% static 'assets/js/vendor/plyr.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js"></script>

</body>

</html>

templates/core/read_cat.html
{% extends 'base.html' %}
<!--{% load static %}-->
{% load course_tags %}
{% block content %}

<!--      <div class="rbt-page-banner-wrapper">-->
<!--        &lt;!&ndash; Start Banner BG Image  &ndash;&gt;-->
<!--        <div class="rbt-banner-image"></div>-->
<!--        &lt;!&ndash; End Banner BG Image  &ndash;&gt;-->

<!--    </div>-->
    <div class="rbt-section-overlayping-top rbt-section-gapBottom">
         <div class="container">
            {% if courses %}
            <!-- Start Card Area -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content" id="rbt-myTabContent">
                        <div class="tab-pane fade show active">
                            <div class="rbt-course-grid-column">

                                <!-- Start Single Course  -->
                                {% for course in courses %}
                                <div class="course-grid-3">
                                    <div class="rbt-card variation-01 rbt-hover">
                                        <div class="rbt-card-img">
                                            <a href="{{course.get_absolute_url}}">
                                                <img src="{{course.featured_image.url}}" alt="Card image">
                                                {% if course.discount == 0 %}
                                                {% else %}
                                                <div class="rbt-badge-3 bg-white">
                                                    <span>{{course.discount}}%</span>
                                                    <span>Off</span>
                                                </div>
                                                {% endif %}
                                            </a>
                                        </div>
                                        <div class="rbt-card-body">
                                            <div class="rbt-card-top">
                                                {% if course.average_review == 0 %}
                                                    <div class="rbt-review">
                                                    </div>
                                                {% else %}
                                                <div class="rbt-review">
                                                   <div class="feature-sin rating">
                                                        <i {% if course.average_review >= 1 %} style="color: orange;"{% endif %} class="fa fa-star"></i>
                                                        <i {% if course.average_review >= 2 %} style="color: orange;"{% endif %} class="fa fa-star"></i>
                                                        <i {% if course.average_review >= 3 %} style="color: orange;"{% endif %} class="fa fa-star"></i>
                                                        <i {% if course.average_review >= 4 %} style="color: orange;"{% endif %} class="fa fa-star"></i>
                                                        <i {% if course.average_review >= 5 %} style="color: orange;"{% endif %} class="fa fa-star"></i>
                                                    </div>
                                                    <span class="rating-count"> {{ course.average_review }}({{course.count_review}} Reviews)</span>
                                                </div>

                                                {% endif %}
                                                <div>
                                                    <a title="Category: {{course.category}}" style="align-items: left;">{{ course.category}}&nbsp;&nbsp;</a>
                                                </div>
                                            </div>

                                            <h4 class="rbt-card-title">
                                                <a href="{{course.get_absolute_url}}">{{course.title}}</a>
                                            </h4>
                                            <ul class="rbt-meta">
                                                <li><i class="feather-book"></i>{{course.video_set.all.count}} Lessons</li>
                                                <li><i class="feather-users"></i>{{course.usercourse_set.all.count}} Student(s)</li>
                                            </ul>
                                            <p class="rbt-card-text" data-toggle="tooltip" title="{{course.description}}">{{course.description|safe|truncatewords:15}}</p>
                                            <div class="rbt-author-meta mb--20">
                                                <div class="rbt-avater">
                                                    <a href="#">
                                                        <img src="{{course.author.user_image.url}}" alt="Sophia Jaymes">
                                                    </a>
                                                </div>
                                                <div class="rbt-author-info">
                                                    By <a href="profile.html">{{course.author.username}}</a> In <a href="#">{{course.category}}</a>
                                                </div>
                                            </div>

                                            <div class="rbt-card-bottom">
                                                {% if course.price == 0 %}
                                                <div class="discount-time">
                                                    <span class="rbt-badge color-success bg-color-success-opacity"> Free</span>
                                                </div>
                                                {% else %}
                                                <div class="rbt-price">
                                                    <span class="current-price">${% discount_calculation course.price course.discount %}</span>
                                                    {% if course.discount == 0 %}
                                                    {% else %}
                                                    <span class="off-price">${{course.price }}</span>
                                                    {% endif %}
                                                </div>
                                                {% endif %}
                                                <a class="rbt-btn-link" href="{{course.get_absolute_url}}">Learn
                                                    More<i class="feather-arrow-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                <!-- End Single Course  -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <h1 align="center">Opps!...</h1>
        <h3 align="center">That category has no courses...</h3>
        {%endif %}
    </div>

    <div class="rbt-separator-mid">
        <div class="container">
            <hr class="rbt-separator m-0">
        </div>
    </div>

{% endblock %}